/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scard;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Long
 */
public class updateInfoForm extends javax.swing.JFrame {
    private theBus thebus;
    private String sothe, hoten, ngaysinh, loaithe, thoihan;
    /**
     * Creates new form updateInfoForm
     */
    public updateInfoForm(String sothe, String hoten, String ngaysinh, String loaithe, String thoihan) {
        initComponents();
        this.thebus = BusForm.thebus;
        this.sothe = sothe;
        this.hoten = hoten;
        this.ngaysinh = ngaysinh;
        this.loaithe = loaithe;
        this.thoihan = thoihan;
        txt_st.setText(sothe);
        txt_ht.setText(hoten);
        txt_ns.setText(ngaysinh);
        txt_lt.setText(loaithe);
        txt_th.setText(thoihan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_st = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ht = new javax.swing.JTextField();
        txt_ns = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_lt = new javax.swing.JTextField();
        txt_th = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_st, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 62, 170, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cập nhật thông tin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, 250, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Họ tên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ngày sinh:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 171, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Loại thẻ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 220, -1, -1));

        txt_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_htActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ht, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 114, 170, 31));
        getContentPane().add(txt_ns, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 163, 170, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Thời hạn:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 269, -1, -1));
        getContentPane().add(txt_lt, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 212, 170, 31));

        txt_th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thActionPerformed(evt);
            }
        });
        getContentPane().add(txt_th, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 261, 170, 31));

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Số thẻ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_htActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_htActionPerformed

    private void txt_thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        String sothe = txt_st.getText();
        String hoten = txt_ht.getText();
        String ngaysinh = txt_ns.getText();
        String loaithe = txt_lt.getText();
        String thoihan = txt_th.getText();
        String arraysend = sothe.concat(".").concat(hoten).concat(".").concat(ngaysinh).concat(".").concat(loaithe).concat(".").concat(thoihan);
        byte[] data = arraysend.getBytes();
        int lc = arraysend.length();
        byte[] cmd= {(byte) 0xA0, (byte) 0x14, (byte) 0x00, (byte) 0x00};
        thebus.sendAPDUtoApplet(cmd, data);
        if((thebus.resAPDU.getSW1() == 0x90) && (thebus.resAPDU.getSW2() == 0x00)){
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công.");
            txt_st.setText("");
            txt_ht.setText("");
            txt_ns.setText("");
            txt_lt.setText("");
            txt_th.setText("");
            setVisible(false);
        }else JOptionPane.showMessageDialog(this, "Chưa cập nhật thành công.");
    }//GEN-LAST:event_btn_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_lt;
    private javax.swing.JTextField txt_ns;
    private javax.swing.JTextField txt_st;
    private javax.swing.JTextField txt_th;
    // End of variables declaration//GEN-END:variables

}
